name: Publish Docker image

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions: 
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: "Login to registry"
        run: |
          export CR_PAT=$TOKEN
          echo $CR_PAT | docker login ghcr.io -u quentinlegot --password-stdin
        env:
          TOKEN: ${{ github.token }}
      - name: "Compile and push"
        run: |
          docker build -t ghcr.io/quentinlegot/base-image-ptft:latest .
          docker push ghcr.io/quentinlegot/base-image-ptft:latest
      
  
          
