name: Publish Docker image

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "Login to registry"
        run: |
          export CR_PAT=$TOKEN
          echo $CR_PAT | docker login -u quentinlegot --password-stdin
        env:
          TOKEN: ${{ secrets.DOCKER_TOKEN }}
      - name: "Compile and push"
        run: |
          docker build -t quentinlegot/base-image-ptft:latest .
          docker push quentinlegot/base-image-ptft:latest
      
  
          
